-- Ejecutar una vez en Supabase SQL Editor.
create table if not exists public.site_content (
  key text primary key,
  image_url text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.future_drops_config (
  section_key text primary key,
  target_date timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.carousel_images (
  id bigint generated by default as identity primary key,
  image_url text not null,
  overlay_text text not null default '',
  display_order integer not null unique check (display_order between 1 and 6),
  created_at timestamptz not null default now()
);

alter table public.carousel_images enable row level security;

drop policy if exists "Public can read carousel images" on public.carousel_images;
create policy "Public can read carousel images"
  on public.carousel_images for select using (true);

drop policy if exists "Authenticated users can manage carousel images" on public.carousel_images;
create policy "Authenticated users can manage carousel images"
  on public.carousel_images for all to authenticated using (true) with check (true);

insert into public.carousel_images (id, image_url, display_order)
select value, '/img/muestra.jpeg', value
from generate_series(1, 6) as value
on conflict (display_order) do nothing;

alter table public.future_drops_config enable row level security;

drop policy if exists "Public can read future drop config" on public.future_drops_config;
create policy "Public can read future drop config"
  on public.future_drops_config for select using (true);

drop policy if exists "Authenticated users can manage future drop config" on public.future_drops_config;
create policy "Authenticated users can manage future drop config"
  on public.future_drops_config for all to authenticated
  using (true) with check (true);

notify pgrst, 'reload schema';

-- Productos de showroom y votos: la clave compuesta impide dos votos del mismo usuario.
create table if not exists public.future_products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  badge text not null,
  tag text not null default 'PRUEBA DE FIT',
  drop_label text not null default 'DROP EN DESARROLLO',
  image_url text not null,
  votes integer not null default 0 check (votes >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.future_products
  add column if not exists tag text not null default 'PRUEBA DE FIT';
alter table public.future_products
  add column if not exists drop_label text not null default 'DROP EN DESARROLLO';

create table if not exists public.future_product_votes (
  product_id bigint not null references public.future_products(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (product_id, user_id)
);

create or replace function public.register_future_product_vote(target_product_id bigint)
returns public.future_products
language plpgsql
security invoker
as $$
declare updated_product public.future_products;
begin
  insert into public.future_product_votes (product_id, user_id)
  values (target_product_id, auth.uid());
  update public.future_products
  set votes = votes + 1
  where id = target_product_id and active = true
  returning * into updated_product;
  return updated_product;
end;
$$;

alter table public.site_content enable row level security;

drop policy if exists "Public can read site content" on public.site_content;
create policy "Public can read site content"
  on public.site_content for select
  using (true);

drop policy if exists "Authenticated users can manage site content" on public.site_content;
create policy "Authenticated users can manage site content"
  on public.site_content for all
  to authenticated
  using (true)
  with check (true);

insert into public.site_content (key, image_url)
values
  ('shop_featured', '/img/muestra.jpeg'),
  ('collection_verano', '/img/f1.jpeg'),
  ('collection_invierno', '/img/f2.jpeg'),
  ('collection_exclusiva', '/img/ferrari.jpeg')
on conflict (key) do nothing;

insert into storage.buckets (id, name, public)
values ('site-content', 'site-content', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can view site content files" on storage.objects;
create policy "Public can view site content files"
  on storage.objects for select
  using (bucket_id = 'site-content');

drop policy if exists "Authenticated users can upload site content files" on storage.objects;
create policy "Authenticated users can upload site content files"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'site-content');
