create extension if not exists pgcrypto;

create table if not exists products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  price numeric(12, 2) not null check (price >= 0),
  material text not null default '',
  color text not null default '',
  product_type text not null check (product_type in ('camiseta', 'buzo', 'balaclava', 'accesorio', 'bolso', 'gafas', 'joya')),
  description text not null default '',
  is_future boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists product_sizes (
  id bigint generated by default as identity primary key,
  product_id uuid not null references products(id) on delete cascade,
  size text not null,
  stock integer not null default 0 check (stock >= 0),
  unique (product_id, size)
);

create table if not exists product_images (
  id bigint generated by default as identity primary key,
  product_id uuid not null references products(id) on delete cascade,
  url text not null,
  position integer not null default 0,
  unique (product_id, position)
);

create table if not exists product_categories (
  product_id uuid not null references products(id) on delete cascade,
  category text not null check (category in ('Novedades', 'Mas-Vendido', 'Hombre', 'Mujer', 'Accesorios', 'General')),
  primary key (product_id, category)
);

create index if not exists product_sizes_product_id_idx on product_sizes(product_id);
create index if not exists product_images_product_id_position_idx on product_images(product_id, position);
create index if not exists product_categories_category_idx on product_categories(category);