-- PostgreSQL app data. user_id is the UUID issued by Supabase Auth.
-- It is intentionally not a foreign key: Supabase Auth is a separate database.

create table if not exists app_users (
  user_id uuid primary key,
  email text,
  display_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  product_type text not null default 'accesorio',
  category text not null default 'general',
  categories text[] not null default '{}',
  price numeric(12, 2) not null default 0 check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  variants jsonb not null default '[]'::jsonb,
  images text[] not null default '{}',
  future_drop boolean not null default false,
  active boolean not null default true,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'shipped', 'completed', 'cancelled')),
  total numeric(12, 2) not null default 0 check (total >= 0),
  shipping_address jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  variant jsonb,
  created_at timestamptz not null default now()
);

create table if not exists addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  label text not null,
  recipient_name text not null,
  phone text not null,
  department text not null,
  city text not null,
  neighborhood text not null,
  address_line text not null,
  address_extra text not null default '',
  notes text not null default '',
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists addresses_one_default_per_user
  on addresses (user_id) where is_default = true;

create table if not exists payment_methods (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  brand text not null,
  last4 text not null check (last4 ~ '^[0-9]{4}$'),
  exp_month smallint not null check (exp_month between 1 and 12),
  exp_year smallint not null,
  holder_name text not null,
  gateway_token text,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create unique index if not exists payment_methods_one_default_per_user
  on payment_methods (user_id) where is_default = true;

create table if not exists site_content (
  content_key text primary key,
  image_url text not null,
  updated_at timestamptz not null default now()
);

create table if not exists future_product_votes (
  product_id bigint not null references products(id) on delete cascade,
  user_id uuid not null,
  created_at timestamptz not null default now(),
  primary key (product_id, user_id)
);

create index if not exists orders_user_id_created_at_idx
  on orders (user_id, created_at desc);
create index if not exists order_items_order_id_idx on order_items (order_id);
create index if not exists products_category_idx on products (category);

-- Example query, also available as listOrdersBySupabaseUserId in src/lib/dbQueries.js:
-- select * from orders where user_id = '00000000-0000-0000-0000-000000000000'::uuid;